name = "my-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
upload = { format = "modules" }

[site]
bucket = ".next"
entry-point = "."

[env.production]
route = ""
zone_id = ""
