name = "my-app"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
upload.format = "service-worker"

[site]
bucket = ".next"
entry-point = "."

[env.production]
route = ""
zone_id = ""
